# Use Python base image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy all project files to container
COPY . /app

# Upgrade pip and install dependencies from requirements.txt
RUN pip install --upgrade pip && \pip install --no-cache-dir -r requirements.txt

# Expose the Flask port
EXPOSE 8080

# Run the app
CMD ["python", "run.py"]

